### ISSUE TITLE
Test QOI in Delphi11

### ISSUE THREAD

**Issue by dbyoung720** [AngusJohnson/TQoiImage#1]
I test QOI in Delphi11:
https://github.com/dbyoung720/TestQOI
In Delphi11, the encoding and decoding efficiency of PNG is about 10 times faster than poi.

When your code is in debug mode, exceptions will occur. In release mode, it is ok.

**Comment by AngusJohnson** [comment]
Hi dbyoung720. Thanks for the feedback. 
Unfortunately I don't have D11, only D10.4 CE but I'll recheck my code and also run your test utility.
Cheers Angus

**Comment by AngusJohnson** [comment]
I've rechecked **Vcl.Imaging.QOI** and I did find (and have now fixed) the bug you mentioned that was causing integer overflow errors. Thanks again for the alert.

I also looked at your own test sample but I didn't compile it as it linked to object code without source.
Nevertheless, modifying your test sample (see newly attached **test.zip** utility), I found ...
  1. the compression of QOI was almost as good as PNG  
  2. QOI loading from file speed was about 3-4 times faster than PNG
  3. QOI saving to file speed was about 15-20 times faster than PNG.

**Comment by dbyoung720** [comment]
qoi_x86.obj compiles qoi.h with vs2019 results.

test sample , png decode / encode , you marked it backwards. Time is the same。

**Comment by AngusJohnson** [comment]
> qoi_x86.obj compiles qoi.h with vs2019 results.

I was wrong in stating that you didn't provide source. Sorry. 
I've now compiled and run your test application but, as far as I can tell, your test neither compresses nor decompresses PNG data, so it's invalid.

>  png decode / encode , you marked it backwards.

I did, another mistake. 
Nevertheless the timings still accurately reflect the very significant speed differences I mentioned above.

**Comment by dbyoung720** [comment]
Caption := Format('PNG encode: %1.4f ms; decode: %1.4f ms', [T1, T2]);
It should be modify:
Caption := Format('PNG encode: %1.4f ms; decode: %1.4f ms', [T2, T1]);

**Comment by AngusJohnson** [comment]
Thanks 👍.
