### ISSUE TITLE
Questions and little issues for TQoiImage on Delphi XE2

### ISSUE THREAD

**Issue by jbfsoftware** [AngusJohnson/TQoiImage#13]
Hi Angus,

Thank you very much for your work on TQoiImage and Image32. 
I have tried your TQoiImage project and the example program on Delphi XE2 and could get it to work with little effort.
There were a few things I had to adjust.

1) Once in The Vcl.Imaging.QOI.pas and once in Unit1.pas you create a bitmap with a width and height argument.
`  Result := TBitmap.Create(img.Width, img.Height);
`
 This did not work on XE2 and I replaced it with:
```
  Result := TBitmap.Create;
  Result.Width := img.Width;
  Result.Height := img.Height;
```
It is an idea to have this updated in the source, for better backward compatibility?

2) XE2 did not accept
`	class function CanLoadFromStream(Stream: TStream): Boolean; override;
`
I guess the function doesn't exist yet in XE2 in the base class so there's nothing to override. By quoting away the override I could compile and get a working result. Maybe it's an idea to make the override conditional. 
Although my solution seems to work I wonder: Do you think of any possible problem for this?

3) I had to quote away
`Vcl.Imaging.Utils in 'Vcl.Imaging.Utils.pas';`
in the main program. It seemed not necessary, and I couldn't find it anywhere (both on XE2 and 10.4).  Could you tell me whether that is a good idea, or where I can get it?

Again, thanks very much for your work.

Best regards, JP.

**Comment by AngusJohnson** [comment]
HI JP. Thank you for the very helpful feedback. I'll update hopefully soonish, but I'm currently occupied with other things.

**Comment by AngusJohnson** [comment]
Hopefully fixed now.
