### ISSUE TITLE
Code parallel

### ISSUE THREAD

**Issue by dbyoung720** [AngusJohnson/TQoiImage#3]
In qoi encoding and decoding code, 
it is better not to use scanline function, best use address pointer, 
so that the code is easy to parallelize.
You can't parallelize with the scanline function.

**Comment by AngusJohnson** [comment]
Thanks for the feedback.

The tricky part is that TBitmap images are always# stored in memory top-down so we can't just set a pointer to the bottom of the pixel array (ie Image.Scanline[Image.Height-1]) and do a straight increment through each pixel. That produces inverted images. I could start at Image.Scanline[0] and decrement the pixel pointer by Image.Width*2 at the end of each line but I doubt this would be any faster than using Scanline and would make the code harder to understand.  Anyhow I'm certainly open to suggestions (especially when supported by code 😜).

#This applies to 'bottom-up' BMP images too.
