### ISSUE TITLE
QoiTest :  function GetFolder can replace  Vcl.FileCtrl.SelectDirectory

### ISSUE THREAD

**Issue by dbyoung720** [AngusJohnson/TQoiImage#9]
QoiTest :  function GetFolder can replace  Vcl.FileCtrl.SelectDirectory. less code.

**Comment by AngusJohnson** [comment]
Less code but sadly broken ...

![folder](https://user-images.githubusercontent.com/5280692/150675700-63e9f115-0650-476d-a450-3b3816d98aba.png)

**Comment by AngusJohnson** [comment]
I've swapped over to TFileOpenDialog which is probably the best of the alternatives.
